/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waterloorocketry_airbrakeplugin_jni_ProcessorCalculations_ControllerState */

#ifndef _Included_com_waterloorocketry_airbrakeplugin_jni_ProcessorCalculations_ControllerState
#define _Included_com_waterloorocketry_airbrakeplugin_jni_ProcessorCalculations_ControllerState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waterloorocketry_airbrakeplugin_jni_ProcessorCalculations_ControllerState
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waterloorocketry_airbrakeplugin_jni_ProcessorCalculations_00024ControllerState_init
  (JNIEnv *, jobject);

/*
 * Class:     com_waterloorocketry_airbrakeplugin_jni_ProcessorCalculations_ControllerState
 * Method:    updateController
 * Signature: (FFFFFFFF)F
 */
JNIEXPORT jfloat JNICALL Java_com_waterloorocketry_airbrakeplugin_jni_ProcessorCalculations_00024ControllerState_updateController
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
