/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waterloorocketry_airbrakeplugin_jni_ProcessorCalculations */

#ifndef _Included_com_waterloorocketry_airbrakeplugin_jni_ProcessorCalculations
#define _Included_com_waterloorocketry_airbrakeplugin_jni_ProcessorCalculations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waterloorocketry_airbrakeplugin_jni_ProcessorCalculations
 * Method:    interpolateDrag
 * Signature: (FFF)F
 */
JNIEXPORT jfloat JNICALL Java_com_waterloorocketry_airbrakeplugin_jni_ProcessorCalculations_interpolateDrag
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
