/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Tools */

#ifndef _Included_jni_Tools
#define _Included_jni_Tools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Tools
 * Method:    bar
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_Tools_bar
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
